no_instances: 200

analysis_name: adult_randoms

dataset_path: adult/adult_cat_mapped.csv

cols:
  - age
  - workclass
  - education-num
  - marital-status
  - occupation
  - relationship
  - race
  - sex
  - capital-gain
  - capital-loss
  - hours-per-week
  - native-country
  - class
